apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.15.100
    path: "/dados/nfsvol"
  mountOptions:
    - nfsvers=4.2
