apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs
